### ISSUE TITLE
A really cool proposition for your plugins

### ISSUE THREAD

**Issue by aquilios** [BoredBean/Instruments4Music#4]
Hey im a mod creator from the official community of lethal company in thunderstore discord, i  have a real proposition to send to you, can we work together in a team to do a mod close to yours but for one and only item? ^^

I explain myself, im trying to code an Ocarina fully playable with a Zelda OOT Look with the 5 notes , UP,Down,Left,Right and A. but im not the yellow of the egg in coding mods like that, so i ask you if it's possible to work with me and another person who's gonna help us to place this Ocarina as Scrap in the facility with spawnrate ect. i can design the HUD and the sounds, my guy the scrap part and you and me or only you the coding of the instrument part of it to play the sounds and the keybinding ^^. So are u in?

you can contact me on Discord : Aquilios

**Comment by BoredBean** [comment]
Hi Aquilios,

Sorry for the late reply. I'm heading out on a business trip this week. 😵
About Discord, I think you're talking about the unofficial LC community, lol

I'm interested in what you're proposing and I'm willing to put in the effort. 
But just for your information, my job takes up a lot of my time, so my progress might be very slow. And because of some network issues, I can't always check Discord messages in a timely manner.

If you're still okay with me joining, please get in touch, Steam works better than Discord for me. Or feel free to use any part of my work that might be helpful, I can provide comments and explanations if needed.
